<?php
/**
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magebit\CheckoutQuickPayPayment\Block\QuickPay;

/** @var QuickPay $block */
/** @var Escaper $escaper */

$methodCode = $block->getMethodCode();
$config = $block->getPaymentConfigByMethod($methodCode);

$logos = $config['paymentLogo'] ?? [];
$description = $config['description'] ?? '';
$label = $config['label'] ?? '';
?>

<?php /* The wire Payment Method directive is required to sit in the root DOM element. */ ?>

<div class="quickpay-method" data-method="<?= $escaper->escapeHtmlAttr($methodCode) ?>">
    <?php if (!empty($logos)): ?>
        <div class="quickpay-logos flex items-center space-x-2">
            <?php foreach ($logos as $logo): ?>
                <img src="<?= $escaper->escapeUrl($logo) ?>" alt="<?= $escaper->escapeHtmlAttr($label) ?>" class="h-8"/>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($description): ?>
        <div class="quickpay-description mt-3 p-4 mb-1 bg-gray-100 rounded-lg">
            <?= $escaper->escapeHtml($description) ?>
        </div>
    <?php endif; ?>
</div>
<div>
    <p class="p-4 bg-gray-100 rounded-lg">
        <?= __('You will be redirected to the QuickPay Gateway to complete payment.') ?>
    </p>
</div>
